### ISSUE TITLE
please provide more info

### ISSUE THREAD

**Issue by Quephara** [xerolinux/xero-welcome-desktop#4]
### please provide more info
love the work you guys did, ive been able to learn more from this app (_and distro_) than i have from being on manjaro for four years. 

my mistake for clicking on the install zsh with ... buttton and following through without knowing what the script does. i switched to fish but cannot get the error `Warning: Could not find '/bin/zsh', starting '/usr/bin/fish' instead.  Please check your profile settings.` off my terminal. please add an undo script  or explanation for what the scripts do. id do with being able to read the script, i can reverse most of what it did.

loving it and thinking of a fresh install though

**Comment by TechXero** [comment]
Hey

Thanks for reporting the issue but that's the wrong place to do so. This repo is for the new tool not the current one.

That being said, I cannot add an undo option sorry. Simply because way I do it is via sed command to profile and shell change command. That's why you only switch when you know what you are doing. Just change shell via the change shell command and set to /bin/fish in konsole settings... 

I don't use fish so no clue if it's any good.

Best of luck

**Comment by Quephara** [comment]
thank you
